name: Release
permissions:
  contents: write

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  release-x86:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
            archive_name: mcumgr-client-windows-x86
          - target: x86_64-unknown-linux-musl
            archive: zip
            archive_name: mcumgr-client-linux-x86
          - target: x86_64-apple-darwin
            archive: zip
            archive_name: mcumgr-client-macos-x86

    steps:
    - uses: actions/checkout@v4
    - name: Build & Release
      uses: rust-build/rust-build.action@v1.4.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        RUSTTARGET: ${{ matrix.target }}
        ARCHIVE_TYPES: ${{ matrix.archive }}
        ARCHIVE_NAME: ${{ matrix.archive_name }}
        EXTRA_FILES: "README.md LICENSE"

  release-macos-universal:
    name: macos-universal
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin

      - name: Build aarch64
        run: cargo build --release --target aarch64-apple-darwin

      - name: Build x86
        run: cargo build --release --target x86_64-apple-darwin

      - name: Make aarch64 zip
        run: >
          zip mcumgr-client-macos-aarch64.zip
          target/aarch64-apple-darwin/release/mcumgr-client
          LICENSE
          README.md

      - name: Upload aarch64 to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: mcumgr-client-macos-aarch64.zip
          tag: ${{ github.ref }}

      - name: Combine Binaries into Universal Binary
        run: >
          lipo -create -output 
          "target/universal/release/mcumgr-client"
          "target/x86_64-apple-darwin/release/mcumgr-client"
          "target/aarch64-apple-darwin/release/mcumgr-client"

      - name: Make universal zip
        run: >
          zip mcumgr-client-macos-universal.zip
          target/universal/release/mcumgr-client
          LICENSE
          README.md

      - name: Upload aarch64 to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: mcumgr-client-macos-universal.zip
          tag: ${{ github.ref }}
