name: Release
permissions:
  contents: write

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          - target: x86_64-apple-darwin
            archive: zip

    steps:
    - uses: actions/checkout@v4
    # - name: Install Linux dependencies
    #   if: matrix.os == 'ubuntu-latest'
    #   run: sudo apt install libudev-dev
    - name: Build & Release
      uses: rust-build/rust-build.action@v1.4.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        RUSTTARGET: ${{ matrix.target }}
        EXTRA_FILES: "README.md LICENSE"
